### ISSUE TITLE
CF_API_KEY did not work with current traefik version

### ISSUE THREAD

**Issue by ddtlabs** [eingress/docker-compose-traefik-letsencrypt-cloudflare#1]
With Traefik current verison you have to use CF_DNS_API_TOKEN instead of CF_API_KEY.
SInce when? Don't know, but it works.

**Comment by eingress** [comment]
Fixed in [df44436c](https://github.com/eingress/docker-compose-traefik-letsencrypt-cloudflare/commit/df44436c973f40b675f0a3d406a3e9463425023d), thanks for the heads up!
